cmdargs:
  verbose: no
  severity: warning
  error-limit: 50
  stat: no
  color: no
  json: no
  env:
    neovim: no
  stdin_display_name: stdin

policies:
  # Experimental
  ProhibitUnusedVariable:
    enabled: no
  ProhibitImplicitScopeVariable:
    enabled: no
