language: python
dist: xenial

git:
  submodules: false

env:
  global:
    PYTEST_ADDOPTS="--cov-report=xml"

stages:
  - name: test
    if: tag IS NOT present
  - name: release
    if: tag IS present

jobs:
  include:
    - name: Python 3.8
      python: "3.8"
      env: TOXENV=py38-cov
    - name: Python 3.7 (integration)
      python: "3.7"
      env: TOXENV=py37-cov
      git:
        # Check out vital.vim for test_cli_vital.
        submodules: true
    - name: Python 2.7
      python: "2.7"
      env: TOXENV=py27-cov
    - name: Python 3.6
      python: "3.6"
      env: TOXENV=py36-cov
    - name: Python 3.5
      python: "3.5"
      env: TOXENV=py35-cov
    - name: Python 3.4
      python: "3.4"
      env: TOXENV=py34-cov

    - stage: release
      script: skip
      install: skip
      after_success: true
      env:
        # PyPI token split into $DPASS1/$DPASS2 (https://github.com/travis-ci/travis.rb/issues/687).
        - secure: "Gvw1PYyfiXR5ZViMwBG9dDqymsVLRJCRjZHxnNGl94H1l+FTvQcMBlwy3aJZvU+hJqkacOEmPB/47hL06pupjvKeUyBDQYX8XW/SZQeblM8/oe4S7ZI1WlH0w0M6XChzmVDaAIuwbS+gd2swU7lV49Vo3iG14ZQVlKG5Z1oEteQ="
        - secure: "OHZdXuOxcEwLM+KWFpYrH54cw/+99EklFXoZ1gOyuJGuMAs2kUfjcmx3mXndKD/UKzZxP6GICHD1YDJok7zUGUcUvT277O6L8aLEbz6sl0PDIRGgG8xHrFbGZNxmTg0nx+qXWXIKmhWRxFT7VItJyocOGCgdfXnHYsiMm+Zqqdw="
      deploy:
        provider: pypi
        distributions: sdist bdist_wheel
        user: __token__
        password: $DPASS1$DPASS2
        on:
          tags: true
          repo: Vimjas/vint

install:
  - pip install tox

script:
  - tox

after_success:
  - |
    if [[ "${TOXENV%-cov}" != $TOXENV ]]; then
      bash <(curl -s https://codecov.io/bash) -f coverage.xml -X fix

      pip install coveralls
      COVERALLS_PARALLEL=true coveralls
    fi

notifications:
  email: false
  webhooks: https://coveralls.io/webhook
