language: python

python:
  - "3.4"

env:
  - TOXENV="py27"
  - TOXENV="py34"
  - TOXENV="coverage"

install:
  - pip install tox
  - if test "$TOXENV" = "coverage"; then pip install coveralls; fi

script:
  - tox

after_success:
  - if test "$TOXENV" = "coverage"; then coveralls; fi

sudo: false

notifications:
  email: false
